// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/echo.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api/echo.proto

It has these top-level messages:
	EchoReq
	EchoRes
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EchoReq struct {
	Rid     string `protobuf:"bytes,1,opt,name=rid" json:"rid,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *EchoReq) Reset()                    { *m = EchoReq{} }
func (m *EchoReq) String() string            { return proto.CompactTextString(m) }
func (*EchoReq) ProtoMessage()               {}
func (*EchoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EchoReq) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *EchoReq) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EchoRes struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Err     string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *EchoRes) Reset()                    { *m = EchoRes{} }
func (m *EchoRes) String() string            { return proto.CompactTextString(m) }
func (*EchoRes) ProtoMessage()               {}
func (*EchoRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EchoRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *EchoRes) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*EchoReq)(nil), "api.EchoReq")
	proto.RegisterType((*EchoRes)(nil), "api.EchoRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Service service

type ServiceClient interface {
	Echo(ctx context.Context, in *EchoReq, opts ...grpc.CallOption) (*EchoRes, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Echo(ctx context.Context, in *EchoReq, opts ...grpc.CallOption) (*EchoRes, error) {
	out := new(EchoRes)
	err := grpc.Invoke(ctx, "/api.Service/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service service

type ServiceServer interface {
	Echo(context.Context, *EchoReq) (*EchoRes, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Service/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Echo(ctx, req.(*EchoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Service_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/echo.proto",
}

func init() { proto.RegisterFile("api/echo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2c, 0xc8, 0xd4,
	0x4f, 0x4d, 0xce, 0xc8, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54,
	0x32, 0xe5, 0x62, 0x77, 0x4d, 0xce, 0xc8, 0x0f, 0x4a, 0x2d, 0x14, 0x12, 0xe0, 0x62, 0x2e, 0xca,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x85, 0x24, 0xb8, 0xd8, 0x73, 0x53,
	0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x98, 0xc0, 0xa2, 0x30, 0x2e, 0x42, 0x5b, 0x31, 0xb2, 0x22,
	0x46, 0x14, 0x45, 0x20, 0x03, 0x53, 0x8b, 0x8a, 0xa0, 0x5a, 0x41, 0x4c, 0x23, 0x5d, 0x2e, 0xf6,
	0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x25, 0x2e, 0x16, 0x90, 0x09, 0x42, 0x3c, 0x7a,
	0x89, 0x05, 0x99, 0x7a, 0x50, 0x37, 0x48, 0x21, 0xf3, 0x8a, 0x93, 0xd8, 0xc0, 0x0e, 0x35, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x39, 0xba, 0x24, 0x5f, 0xba, 0x00, 0x00, 0x00,
}
